apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: vue
  name: vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
      - image: fingertip/vue-kubernetes:latest
        imagePullPolicy: Always
        name: vue
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
